# Generated by Django 5.1.1 on 2024-09-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='api.attachment'),
        ),
        migrations.AddField(
            model_name='crm',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='crms', to='api.attachment'),
        ),
    ]
